export const questionsAndAnswers = [
  { question: "In more recent times, the Master Scientist philosophical doctrine has come to be known as ___.", answer: "Scientism" },
  { question: "According to ________, philosophy is rightly called the knowledge of the truth.", answer: "Aristotle" },
  { question: "An important characteristic of philosophy is that it consists in the constant and unwavering disposition to seek the truth. True or False ____", answer: "True" },
  { question: "Examination and confirmation of the universal acceptance of moral views held by human beings or the society is the responsibility of ______", answer: "Descriptive ethics" },
  { question: "Observation and understanding supernatural phenomenon and control processes is the main task of _______", answer: "Science" },
  { question: "Philosophy has no univocal definition. True or False _____", answer: "True" },
  { question: "The method of _____ takes reason to be the sole means of acquiring philosophical knowledge.", answer: "Rationalism" },
  { question: "The philosophical idea that establishes the world as a product of a single understanding substance is known as ______", answer: "Monism" },
  { question: "The method of rationalism takes reason to be the sole means of acquiring philosophical knowledge. True or False ________", answer: "True" },
  { question: "The critical or transcendental method of philosophy ______takes stock of the arguments of empiricism and rationalism and builds a new system of tremendous importance in the history of philosophic thought.", answer: "Kant" },
  { question: "______ method of philosophy consists in the constructive dialectical process of opposition and reconciliation.", answer: "Hegel" },
  { question: "Identifying a complex argument involves a complex reasoning. True or False ____", answer: "True" },
  { question: "_______ arguments are those in which the premises do not lead to the conclusion with certainty.", answer: "Inductive" },
  { question: "The branch of philosophy that studies reality in its most comprehensive scope is ____", answer: "Metaphysics" },
  { question: "_____ is also referred to as the science of human conduct.", answer: "Ethics" },
  { question: "To claim the knowledge of anything, one must possess correct_____ about the thing.", answer: "Information" },
  { question: "The idea that only change is constant is from ______.", answer: "Heraclitus" },
  { question: "We have knowledge only when we can NOT provide reasons and evidence for our claims. True or False ____", answer: "False" },
  { question: "According to _______, water is the primary source of all things in the universe.", answer: "Thales" },
  { question: "According to ____ happiness could best be achieved by living a balanced life and avoiding excess by pursuing a golden mean in everything.", answer: "Aristotle" },
  { question: "To the ______ we can never know the true inner substance of things, only how they appear to us.", answer: "Sceptics" },
  { question: "Nationalist and ideological philosophy is also known as a sub of______ in African philosophy.", answer: "Professional philosophy" },
  { question: "_______was largely a religious philosophy which became a strong influence on early Christianity (especially on St. Augustine).", answer: "Neo-Platonism" },
  { question: "Condensation and Refraction theory was developed to justify ___ as the primary source of all things.", answer: "Air" },
  { question: "The weakness or strength of an Inductive argument depends on the degree of evidence contained in the conclusion. True or False ______", answer: "True" },
  { question: "Denotative definition is one that attempts to identify the extension of the term in a question. True or False ______", answer: "True" },
  { question: "According to the Law of Identity, not everything you say presupposes that thing. True or False ____", answer: "False" },
  { question: "In a disjunctive syllogism, the first premise is a _______.", answer: "Disjunction" },
  { question: "It is through the possession of language by human beings that their thought and conduct are made possible. True or False _______", answer: "True" },
  { question: "Argumentum ad Baculum means ______", answer: "Appeal to force" },
  { question: "_____ fallacy mostly occurs when we misinterpret someone’s original statement or intention.", answer: "Amphiboly" },
  { question: "Fallacy of Begging the question is also known as ____", answer: "Petito-principii" },
  { question: "______definition does not attempt overcoming ambiguity or to achieve precision rather it focuses on formulating a theory within which a fully correct definition of important terms could be stated.", answer: "Theoretical" },
  { question: "According to the law of_______, you cannot refuse to be this and also refuse to be the other.", answer: "Excluded middle" },
  { question: "The law of _______ tells you that a thing must be one thing or another thing.", answer: "Non-contradiction" },
  { question: "Philosophy grew out of", answer: "Wonder and Curiosity" },
  { question: "One of the following is a fundamental factor that determines the definition of philosophy", answer: "Issues" },
  { question: "To wonder about life and every issue that borders on human existence is", answer: "Philosophical activity" },
  { question: "The conception of philosophy as a person’s attitude or principle is called", answer: "Under labourer" },
  { question: "The empiricist conception of truth or reality is based on", answer: "Sense experience" },
  { question: "Which of the following is referred to as the science of reasoning?", answer: "Logic" },
  { question: "The idea of epistemology was explained using the idea of world of 'Forms' by", answer: "Plato" },
  { question: "Which of the following philosophers is NOT a member of the Medieval age of philosophy?", answer: "Berkeley" },
  { question: "The medieval philosophers employed philosophy to teach", answer: "Religion" },
  { question: "An attempt to become aware and to doubt all preconceptions and the essence in order to ensure certainty in the process is called", answer: "Scepticism" },
  { question: "Which of the following grew after the traditional branches of philosophy?", answer: "Feminism" },
  { question: "The author of synthetic a priori knowledge is", answer: "Kant" },
  { question: "Philosophical knowledge is believed to follow the logic of", answer: "Proposition" },
  { question: "Which of the following is an Islamic philosopher in the Medieval period?", answer: "Averroes" },
  { question: "What kind of argument is 'Most mechanics are dark in complexion, Yisa is a mechanic, therefore Yisa is dark in complexion'?", answer: "Inductive" },
  { question: "Which of the following branches of philosophy has been defined as the science of being as being?", answer: "Metaphysics" },
  { question: "The first philosopher to confess that 'the only thing I know is that I know nothing' is", answer: "Socrates" },
  { question: "Which group holds a relativistic view of knowledge?", answer: "Sophism" },
  { question: "The Era of the Ionians was dominated by the following philosophers EXCEPT", answer: "Zeno of Citium" },
  { question: "Natural philosophy gave rise to the following EXCEPT", answer: "Culture" },
  { question: "The Greek philosophers were said to have had contact with and influenced by", answer: "Egyptian philosophy" },
  { question: "That pleasure is the most important pursuit of mankind, and that we should always act so as to maximize our own pleasure is the philosophical position of the", answer: "Hedonists" },
  { question: "What are the opposing doctrines that characterized The Age of Reason and The Age of Enlightenment?", answer: "Rationalism and Empiricism" },
  { question: "What form of function is performed by language when the utterance operates to evoke action from the hearer?", answer: "Directive" },
  { question: "'I shall contest the next election,' is an example of what function of language?", answer: "Performative" },
  { question: "Which of the following is NOT an informal fallacy?", answer: "Four term" },
  { question: "What fallacy is committed in the argument: 'Only man is rational. But no woman is a man. Therefore, no woman is rational.'?", answer: "Equivocation" },
  { question: "What kind of definitions is directed at developing a coherent theoretical account of the subject at hand?", answer: "Theoretical" },
  { question: "'All students' falls under what category of proposition?", answer: "Universal affirmative" },
  { question: "Recursive definition is sometimes referred to as", answer: "Inductive" },
  { question: "The words Definiendum and definiens are key concepts in the method of definition by", answer: "Genus and Difference" }
];
